/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Metodos_SQL.ConexionBD;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author jugad
 */
public class EstudiantesPrimerCurso extends javax.swing.JFrame {

    /**
     * Creates new form EstudiantesPrimerCurso
     */
    
    ImageIcon icon;
    public EstudiantesPrimerCurso() {
        initComponents();
        setLocationRelativeTo(null);
        icon = new ImageIcon("image/icon.jpg");
        setIconImage(icon.getImage());
    }
    
    public void mostrar(String tabla, String codigo)
    {
        
        String sql = "SELECT  codigo_programa, nombre_del_programa, periodo, inscritos, admitidos, matriculados FROM "+tabla+" WHERE codigo_programa = "+codigo ;
        Statement st;
        ConexionBD con = new ConexionBD();
        Connection conexion = con.conectar();
        System.out.println(sql);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("codigo_programa");
        model.addColumn("nombre_del_programa");
        model.addColumn("periodo");
        model.addColumn("Inscritos");
        model.addColumn("Admitidos");
        model.addColumn("Matriculados");
        
        visor.setModel(model);
        String[] datos = new String[6];
        
        try
        {
            st = (Statement) conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                model.addRow(datos);
                
            }
        }catch(SQLException e)
        {
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaCarreras = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        visor = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnInsertar = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaCarreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "107859 - Tecnico profesional en soporte informatico", "107860 - Tecnologo en desarrollo de software", "107861 - Ingenieria de software", "91390 - Tecnica profesional produccion grafica", "91389 - Tecnologia en diseño publlicitario", "91388 - Profesional en diseño grafico", "104668 - Tecnico proceso diseño de modas", "53509 - Tecnologia en gestion de diseño de modas", "104671 - Profesional en diseño y administracion de modas" }));
        listaCarreras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaCarrerasActionPerformed(evt);
            }
        });
        getContentPane().add(listaCarreras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        visor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(visor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 595, 175));

        btnRegresar.setBackground(new java.awt.Color(250, 17, 17));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorderPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, -1, -1));

        btnInsertar.setBackground(new java.awt.Color(250, 17, 17));
        btnInsertar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertar.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 3)); // NOI18N
        lblUsuario.setText("jLabel2");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/tablasSief.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaCarrerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaCarrerasActionPerformed
        // TODO add your handling code here:
        
        String lista = listaCarreras.getSelectedItem().toString();
        
        if(lista.equals("107859 - Tecnico profesional en soporte informatico"))
        {
            mostrar("nuevoprograma", "107859");
        }
        else if(lista.equals("107860 - Tecnologo en desarrollo de software"))
        {
            mostrar("nuevoprograma", "107860");
        }
        else if(lista.equals("107861 - Ingenieria de software"))
        {
            mostrar("nuevoprograma", "107861");
        }
        else if(lista.equals("91390 - Tecnica profesional produccion grafica"))
        {
            mostrar("nuevoprograma", "91390");
        }
        else if(lista.equals("91389 - Tecnologia en diseño publlicitario"))
        {
            mostrar("nuevoprograma","91389");
        }
        else if(lista.equals("91388 - Profesional en diseño grafico"))
        {
            mostrar("nuevoprograma", "91388");
        }
        else if(lista.equals("104668 - Tecnico proceso diseño de modas"))
        {
            mostrar("nuevoprograma", "104668");
        }
        else if(lista.equals("53509 - Tecnologia en gestion de diseño de modas"))
        {
            mostrar("nuevoprograma", "53509");
        }
        else if(lista.equals("104671 - Profesional en diseño y administracion de modas"))
        {
            mostrar("nuevoprograma", "104671");
        }
                
    }//GEN-LAST:event_listaCarrerasActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        
        String lista = listaCarreras.getSelectedItem().toString();
        String usuario = this.lblUsuario.getText();
        
        if(lista.equals("107859 - Tecnico profesional en soporte informatico"))
        {
            
            Modificar ventana = new Modificar();
            ventana.setVisible(true);      
            ventana.lblCarrera.setText("107859");
            ventana.lblNombreCarrera.setText("Tecnico profesional en soporte informatico");
            String codigo = ventana.lblCarrera.getText();
            String nombre = ventana.lblNombreCarrera.getText();
            ventana.campoCodigo.setText(codigo);
            ventana.campoNombre.setText(nombre);
            ventana.lblUsuario.setText(usuario);
           
        }
        else if(lista.equals("107860 - Tecnologo en desarrollo de software"))
        {
            Modificar ventana = new Modificar();
            ventana.setVisible(true);
            ventana.lblCarrera.setText("107860");
            ventana.lblNombreCarrera.setText("Tecnologo en desarrollo de software");
            String codigo = ventana.lblCarrera.getText();
            String nombre = ventana.lblNombreCarrera.getText();           
            ventana.campoCodigo.setText(codigo);
            ventana.campoNombre.setText(nombre);
            ventana.lblUsuario.setText(usuario);
            
                    
        }
        else if(lista.equals("107861 - Ingenieria de software"))
        {
            Modificar ventana = new Modificar();
            ventana.setVisible(true);
            ventana.lblCarrera.setText("107861");
            ventana.lblNombreCarrera.setText("Ingenieria de software");
            String codigo = ventana.lblCarrera.getText();
            String nombre = ventana.lblNombreCarrera.getText();
            ventana.campoCodigo.setText(codigo);
            ventana.campoNombre.setText(nombre);
            ventana.lblUsuario.setText(usuario);
        }
        else if(lista.equals("91390 - Tecnica profesional produccion grafica"))
        {
            Modificar ventana = new Modificar();
            ventana.setVisible(true);
            ventana.lblCarrera.setText("91390");
            ventana.lblNombreCarrera.setText("Tecnica profesional produccion grafica");
            String codigo = ventana.lblCarrera.getText();
            String nombre = ventana.lblNombreCarrera.getText();
            ventana.campoCodigo.setText(codigo);
            ventana.campoNombre.setText(nombre);
            ventana.lblUsuario.setText(usuario);
        }
        else if(lista.equals("91389 - Tecnologia en diseño publlicitario"))
        {
            Modificar ventana = new Modificar();
            ventana.setVisible(true);
            ventana.lblCarrera.setText("91389");
            ventana.lblNombreCarrera.setText("Tecnologia en diseño publlicitarioa");
            String codigo = ventana.lblCarrera.getText();
            String nombre = ventana.lblNombreCarrera.getText();
            ventana.campoCodigo.setText(codigo);
            ventana.campoNombre.setText(nombre);
            ventana.lblUsuario.setText(usuario);
        }
        else if(lista.equals("91388 - Profesional en diseño grafico"))
        {
            Modificar ventana = new Modificar();
            ventana.setVisible(true);
            ventana.lblCarrera.setText("91388");
            ventana.lblNombreCarrera.setText("Profesional en diseño grafico");
            String codigo = ventana.lblCarrera.getText();
            String nombre = ventana.lblNombreCarrera.getText();
            ventana.campoCodigo.setText(codigo);
            ventana.campoNombre.setText(nombre);
            ventana.lblUsuario.setText(usuario);
        }
        else if(lista.equals("104668 - Tecnico proceso diseño de modas"))
        {
            Modificar ventana = new Modificar();
            ventana.setVisible(true);
            ventana.lblCarrera.setText("104668");
            ventana.lblNombreCarrera.setText("Tecnico proceso diseño de modas");
            String codigo = ventana.lblCarrera.getText();
            String nombre = ventana.lblNombreCarrera.getText();
            ventana.campoCodigo.setText(codigo);
            ventana.campoNombre.setText(nombre);
            ventana.lblUsuario.setText(usuario);
        }
        else if(lista.equals("53509 - Tecnologia en gestion de diseño de modas"))
        {
            Modificar ventana = new Modificar();
            ventana.setVisible(true);
            ventana.lblCarrera.setText("53509");
            ventana.lblNombreCarrera.setText("Tecnologia en gestion de diseño de modas");
            String codigo = ventana.lblCarrera.getText();
            String nombre = ventana.lblNombreCarrera.getText();
            ventana.campoCodigo.setText(codigo);
            ventana.campoNombre.setText(nombre);
            ventana.lblUsuario.setText(usuario);
        }
        else if(lista.equals("104671 - Profesional en diseño y administracion de modas"))
        {
            Modificar ventana = new Modificar();
            ventana.setVisible(true);
            ventana.lblCarrera.setText("104671");
            ventana.lblNombreCarrera.setText("Profesional en diseño y administracion de modas");
            String codigo = ventana.lblCarrera.getText();
            String nombre = ventana.lblNombreCarrera.getText();
            ventana.campoCodigo.setText(codigo);
            ventana.campoNombre.setText(nombre);
            ventana.lblUsuario.setText(usuario);
        }
        
    }//GEN-LAST:event_btnInsertarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstudiantesPrimerCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstudiantesPrimerCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstudiantesPrimerCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstudiantesPrimerCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstudiantesPrimerCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblUsuario;
    private javax.swing.JComboBox<String> listaCarreras;
    public javax.swing.JTable visor;
    // End of variables declaration//GEN-END:variables
}
