/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;
import Metodos_SQL.MetodosSQL;
import static java.lang.Integer.parseInt;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.NoSuchProviderException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Aula 103
 */
public class Modificar extends javax.swing.JFrame {

    private static String emailFrom = "normanlucciano@gmail.com";
    private static String passwordFrom = "heiljwlpxtelsbps";
    private String emailTo;
    private String subject;
    private String content;

    private Properties mProperties;
    private Session mSession;
    private MimeMessage mCorreo;
    
    ImageIcon icon;
    public Modificar() {
        initComponents();
        setLocationRelativeTo(null);
        icon = new ImageIcon("image/icon.jpg");
        setIconImage(icon.getImage());
        mProperties = new Properties();
    }
    
    private void createEmail() {
        emailTo = "jugada1603@gmail.com";
        subject = "Nuevo cambio en los indicadores";
        content = "Un usario ha hecho nuevos cambios en los indicadores de la informacion estadisitica estudaintil";
        
         // Simple mail transfer protocol
         
         /*
        mProperties.put("mail.smtp.host", "smtp.gmail.com");
        mProperties.put("mail.smtp.ssl.trust", "smtp.gmail.com");
        mProperties.setProperty("mail.smtp.starttls.enable", "true");
        mProperties.setProperty("mail.smtp.port", "587");
        mProperties.setProperty("mail.smtp.user",emailFrom);
        mProperties.setProperty("mail.smtp.ssl.protocols", "TLSv1.2");
        mProperties.setProperty("mail.smtp.auth", "true");
        */
         
         mProperties.put("mail.smtp.host", "smtp.gmail.com");
         mProperties.put("mail.smtp.auth", "true");
         mProperties.put("mail.smtp.port", "465");
         mProperties.put("mail.smtp.socketFactory.port", "465");
         mProperties.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
         mProperties.put("mail.smtp.ssl.protocols", "TLSv1.2");
         
        mSession = Session.getDefaultInstance(mProperties);
        
        
        try {
            mCorreo = new MimeMessage(mSession);
            mCorreo.setFrom(new InternetAddress(emailFrom));
            mCorreo.setRecipient(Message.RecipientType.TO, new InternetAddress(emailTo));
            mCorreo.setSubject(subject);
            mCorreo.setText(content, "ISO-8859-1", "html");
                     
            
        } catch (AddressException ex) {
            Logger.getLogger(Modificar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            Logger.getLogger(Modificar.class.getName()).log(Level.SEVERE, null, ex);
       
        
        
        }
    }
    
    
    private void sendEmail() {
        try {
            Transport mTransport = mSession.getTransport("smtp");
            mTransport.connect(emailFrom, passwordFrom);
            mTransport.sendMessage(mCorreo, mCorreo.getRecipients(Message.RecipientType.TO));
            mTransport.close();
            
            JOptionPane.showMessageDialog(null, "Correo enviado");
        } catch (NoSuchProviderException ex) {
            Logger.getLogger(Modificar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MessagingException ex) {
            Logger.getLogger(Modificar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    MetodosSQL sql = new MetodosSQL();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        campoNombre = new javax.swing.JTextField();
        campoPeriodo = new javax.swing.JTextField();
        campoInscritos = new javax.swing.JTextField();
        campoAdmitidos = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblCarrera = new javax.swing.JLabel();
        lblNombreCarrera = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        campoGraduados = new javax.swing.JTextField();
        lblUsuario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo del programa:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, -1, -1));

        jLabel2.setText("Nombre del programa:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        jLabel3.setText("Periodo: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        jLabel4.setText("Inscritos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        jLabel5.setText("Admitidos:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        campoCodigo.setText("Codigo");
        campoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(campoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 150, -1));

        campoNombre.setText("Nombre");
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });
        getContentPane().add(campoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 150, -1));

        campoPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPeriodoActionPerformed(evt);
            }
        });
        getContentPane().add(campoPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 150, -1));
        getContentPane().add(campoInscritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 150, -1));
        getContentPane().add(campoAdmitidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 150, -1));

        btnInsertar.setBackground(new java.awt.Color(255, 255, 255));
        btnInsertar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsertar.setForeground(new java.awt.Color(250, 17, 17));
        btnInsertar.setText("Insertar");
        btnInsertar.setBorderPainted(false);
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 100, -1));

        btnRegresar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(250, 17, 17));
        btnRegresar.setText("Regresar");
        btnRegresar.setBorderPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 100, -1));

        lblCarrera.setFont(new java.awt.Font("Segoe UI", 1, 3)); // NOI18N
        lblCarrera.setForeground(new java.awt.Color(255, 255, 255));
        lblCarrera.setText("a");
        getContentPane().add(lblCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 80, -1, -1));

        lblNombreCarrera.setFont(new java.awt.Font("Segoe UI", 1, 3)); // NOI18N
        lblNombreCarrera.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCarrera.setText("b");
        getContentPane().add(lblNombreCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabel7.setText("Graduados");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, -1));

        campoGraduados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoGraduadosActionPerformed(evt);
            }
        });
        getContentPane().add(campoGraduados, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 150, -1));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 3)); // NOI18N
        lblUsuario.setText("jLabel8");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/insertar.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoActionPerformed

    private void campoPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPeriodoActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        
        createEmail();
        sendEmail();
        String inscritos = campoInscritos.getText();
        String admitidos = campoAdmitidos.getText();
        String graduados = campoGraduados.getText();
        
        int inscritosInteger = parseInt(inscritos);
        int admitidosInteger = parseInt(admitidos);
        int graduadosInteger = parseInt(graduados);
        
        int guardarInformacion = sql.guardarInformacionTabla(campoCodigo.getText(), campoNombre.getText(), campoPeriodo.getText(), inscritosInteger, admitidosInteger, admitidosInteger, graduadosInteger);
        System.out.println("Registro exitoso");
        System.out.println(guardarInformacion);
        
        String nombreUsuarioAdministrador = sql.buscarNombreAdministrador(this.lblUsuario.getText());
        System.out.println(nombreUsuarioAdministrador);
        String correo = sql.buscarCorreo(this.lblUsuario.getText());
        System.out.println(correo);
        
        
        
        
        sql.guardarTablaModificacion(nombreUsuarioAdministrador, this.lblUsuario.getText(), correo, this.campoNombre.getText());
       
        
        
        //Codigo para envio del correo al adinistrado principal de la aplicacion
        this.dispose();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void campoGraduadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoGraduadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoGraduadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JTextField campoAdmitidos;
    public javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoGraduados;
    private javax.swing.JTextField campoInscritos;
    public javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JLabel lblCarrera;
    public javax.swing.JLabel lblNombreCarrera;
    public javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
