/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Metodos_SQL.ConexionBD;
import Metodos_SQL.MetodosSQL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jugad
 */
public class SaberPro extends javax.swing.JFrame {

    /**
     * Creates new form SaberPro
     */
    public SaberPro() {
        initComponents();
    }
    
    
    public void mostrar(String codigo)
    {
        
        String sql = "SELECT  codigo_programa, nombre_programa, numero_estudiantes, competencia_ciudadana, razonamiento_cuantitativo, comunicacion_escrita, ingles, lectura_critica FROM saberpro WHERE codigo_programa = "+codigo ;
        Statement st;
        ConexionBD con = new ConexionBD();
        Connection conexion = con.conectar();
        System.out.println(sql);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("codigo_programa");
        model.addColumn("nombre_programa");
        model.addColumn("numero_estudiantes");
        model.addColumn("competencia_ciudadana");
        model.addColumn("razonamiento_cuantitativo");
        model.addColumn("comunicacion_escrita");
        model.addColumn("ingles");
        model.addColumn("lectura_critica");
 
        
        visor.setModel(model);
        String[] datos = new String[8];
        
        try
        {
            st = (Statement) conexion.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next())
            {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                datos[4] = rs.getString(5);
                datos[5] = rs.getString(6);
                datos[6] = rs.getString(7);
                datos[7] = rs.getString(8);
            

                model.addRow(datos);
                
            }
        }catch(SQLException e)
        {
            
        }
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        visor = new javax.swing.JTable();
        comboConsultar = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        visor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(visor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 830, 300));

        comboConsultar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "107859 - Tecnico profesional en soporte informatico", "107860 - Tecnologo en desarrollo de software", "107861 - Ingenieria de software" }));
        comboConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(comboConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 340, -1));

        jButton1.setText("Insertar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 70, -1, -1));

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, -1, -1));

        lblUsuario.setText("jLabel1");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboConsultarActionPerformed
        // TODO add your handling code here:
        
          String lista = comboConsultar.getSelectedItem().toString();
        
        if(lista.equals("107859 - Tecnico profesional en soporte informatico"))
        {
            mostrar("107859");
            System.out.println("a");
        }
        else if(lista.equals("107860 - Tecnologo en desarrollo de software"))
        {
            mostrar("107860");
        }
        else if(lista.equals("107861 - Ingenieria de software"))
        {
            mostrar("107861");
        }
    }//GEN-LAST:event_comboConsultarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        String lista = comboConsultar.getSelectedItem().toString();
        String usuario = this.lblUsuario.getText();
        
        if(lista.equals("107859 - Tecnico profesional en soporte informatico"))
        {
            
            InsertarSaberPro ventana = new InsertarSaberPro();
            ventana.setVisible(true);      
            ventana.lblCarrera.setText("107859");
            ventana.lblNombreCarrera.setText("Tecnico profesional en soporte informatico");
            String codigo = ventana.lblCarrera.getText();
            String nombre = ventana.lblNombreCarrera.getText();
            ventana.campoCodigo.setText(codigo);
            ventana.campoNombre.setText(nombre);
            ventana.lblUsuario.setText(usuario);
           
        }
        else if(lista.equals("107860 - Tecnologo en desarrollo de software"))
        {
            Modificar ventana = new Modificar();
            ventana.setVisible(true);
            ventana.lblCarrera.setText("107860");
            ventana.lblNombreCarrera.setText("Tecnologo en desarrollo de software");
            String codigo = ventana.lblCarrera.getText();
            String nombre = ventana.lblNombreCarrera.getText();           
            ventana.campoCodigo.setText(codigo);
            ventana.campoNombre.setText(nombre);
            ventana.lblUsuario.setText(usuario);
            
                    
        }
        else if(lista.equals("107861 - Ingenieria de software"))
        {
            Modificar ventana = new Modificar();
            ventana.setVisible(true);
            ventana.lblCarrera.setText("107861");
            ventana.lblNombreCarrera.setText("Ingenieria de software");
            String codigo = ventana.lblCarrera.getText();
            String nombre = ventana.lblNombreCarrera.getText();
            ventana.campoCodigo.setText(codigo);
            ventana.campoNombre.setText(nombre);
            ventana.lblUsuario.setText(usuario);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaberPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaberPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaberPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaberPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaberPro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> comboConsultar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable visor;
    // End of variables declaration//GEN-END:variables
}
