/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;
import Vistas.RegistroAdmin;
import Vistas.OtorgarPermisos;
import Metodos_SQL.MetodosSQL;
import java.io.IOException;
import java.net.URISyntaxException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jugad
 */
public class SIEF extends javax.swing.JFrame {

    
    /**
     * Creates new form SIEF
     */
    
    ImageIcon icon;
    public SIEF() {
        setSize(600,460);
        initComponents();
        setLocationRelativeTo(null);
        icon = new ImageIcon("image/icon.jpg");
        setIconImage(icon.getImage());
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        
    }
    
    public void cerrarSesion()
    {
        this.dispose();
    }
    
    
    public void metodoURL(String url)
    {
        if(java.awt.Desktop.isDesktopSupported())
        {
            java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
            
            if(desktop.isSupported(java.awt.Desktop.Action.BROWSE))
            {
                try{
                    java.net.URI uri = new java.net.URI(url);
                    desktop.browse(uri);
                    
                }catch(IOException | URISyntaxException e)
                {
                    
                }
            }
        }
    }
    
    MetodosSQL metodos = new MetodosSQL();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        funcionAdmin = new javax.swing.JComboBox<>();
        infEstadistico = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        infCaracterizacion = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnPerfil = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        comboConsultar = new javax.swing.JComboBox<>();
        btnCerrarSesion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Caracterización:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 504, -1, -1));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 70, 20));

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 3)); // NOI18N
        lblTipo.setText("jLabel4");
        getContentPane().add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, -1, 20));

        funcionAdmin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        funcionAdmin.setForeground(new java.awt.Color(255, 255, 255));
        funcionAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Registro usuario", "Otorgar permisos", "Modificar indicador", "Actividad en indicadores" }));
        funcionAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcionAdminActionPerformed(evt);
            }
        });
        getContentPane().add(funcionAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 170, -1));

        infEstadistico.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        infEstadistico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------", "Informe estadistico 2012-1", "Informe estadistico 2012-2", "Informe estadistico 2013-1", "Informe estadistico 2013-2", "Informe estadistico 2014-1", "Informe estadistico 2014-2", "Informe estadistico 2015-1", "Informe estadistico 2015-2", "Informe estadistico 2016-1", "Informe estadistico 2016-2", "Informe estadistico 2017-1", "Informe estadistico 2017-2", "Informe estadistico 2018-1", "Informe estadistico 2018-2", "Informe estadistico 2019-1", "Informe estadistico 2019-2", "Informe estadistico 2020-1", "Informe estadistico 2020-2", "Informe estadistico 2021-1", "Informe estadistico 2021-2", "Informe estadistico 2022-1" }));
        infEstadistico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infEstadisticoActionPerformed(evt);
            }
        });
        getContentPane().add(infEstadistico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Informes estadisticos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        infCaracterizacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        infCaracterizacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----------", "Admitidos 2017-1", "Admitidos 2017-2", "Admitidos 2018-1", "Admitidos 2018-2", "Admitidos 2019-1", "Admitidos 2019-2", "Admitidos 2020-1", "Admitidos 2020-2", "Admitidos 2021-1", "Admitidos 2021-2", "Admitidos 2022-1" }));
        infCaracterizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infCaracterizacionActionPerformed(evt);
            }
        });
        getContentPane().add(infCaracterizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 180, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 210, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Consultar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 20));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Usuario:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        btnPerfil.setBackground(new java.awt.Color(233, 233, 233));
        btnPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Usuario sin fondo.png"))); // NOI18N
        btnPerfil.setBorder(null);
        btnPerfil.setContentAreaFilled(false);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 3)); // NOI18N
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 70, 20));

        comboConsultar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        comboConsultar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Poblacion estudiantil", " ", "Estudiantes de primer curso", "Inscritos", "Admitidos", "Matriculados", "Graduados" }));
        comboConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(comboConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 180, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(233, 233, 233));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/cerrarSesion-removebg-preview (1).png"))); // NOI18N
        btnCerrarSesion.setBorderPainted(false);
        btnCerrarSesion.setContentAreaFilled(false);
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/Sief1.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void funcionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcionAdminActionPerformed
        // TODO add your handling code here:
        
        String lista = funcionAdmin.getSelectedItem().toString();
        
        if(lista.equals("Registro usuario"))
        {
            RegistroAdmin ventana = new RegistroAdmin();
            ventana.setVisible(true);
        }
        else if(lista.equals("Otorgar permisos"))
        {
            OtorgarPermisos ventana = new OtorgarPermisos();
            ventana.setVisible(true);
        }
        
        else if(lista.equals("Modificar indicador"))
        {
            String usuario = this.lblUsuario.getText();
            EstudiantesPrimerCurso ventana = new EstudiantesPrimerCurso();
            ventana.lblUsuario.setText(usuario);
            ventana.setVisible(true);
            
        }
        else if(lista.equals("Actividad en indicadores"))
        {
            ActividadIndicadores ventana = new ActividadIndicadores();
            ventana.mostrar();
            ventana.setVisible(true);

        }    
                    

          
    }//GEN-LAST:event_funcionAdminActionPerformed

    private void infEstadisticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infEstadisticoActionPerformed
        // TODO add your handling code here:
        String lista = infEstadistico.getSelectedItem().toString();
        
        if(lista.equals("----------"))
        {
            
            System.out.println("Resultado correcto ");
        }
        else if(lista.equals("Informe estadistico 2012-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2012_01.pdf");
        }
        else if(lista.equals("Informe estadistico 2012-2"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2012_02.pdf");
        }
        else if(lista.equals("Informe estadistico 2013-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2013_01.pdf");
        }
        else if(lista.equals("Informe estadistico 2013-2"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2013_02.pdf");
        }
        else if(lista.equals("Informe estadistico 2014-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2014_01.pdf");
        }
        else if(lista.equals("Informe estadistico 2014-2"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2014_02.pdf");
        }
        else if(lista.equals("Informe estadisctico 2015-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2015_01.pdf");
        }
        else if(lista.equals("Informe estadistico 2015-2"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2015_02.pdf");
        }
        else if(lista.equals("Informe estadistico 2016-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2016_01.pdf");
        }
        else if(lista.equals("Informe estadistico 2016-2"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2016_02.pdf");
        }
        else if(lista.equals("Informe estadistico 2017-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2017_01.pdf");
        }
        else if(lista.equals("Informe estadistico 2017-2"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2017_02.pdf");
        }
        else if(lista.equals("Informe estadistico 2018-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2018_01.pdf");
        }
        else if(lista.equals("Informe estadistico 2018-2"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2018_02.pdf");
        }
        else if(lista.equals("Informe estadistico 2019-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2019_01.pdf");
        }
        else if(lista.equals("Informe estadistico 2019-2"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2019_02.pdf");
        }
        else if(lista.equals("Informe estadistico 2020-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2020_01.pdf");
        }
        else if(lista.equals("Informe estadistico 2020-2"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2020_02.pdf");
        }
        else if(lista.equals("Informe estadistico 2021-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2021_01.pdf");
        }
        else if(lista.equals("Informe estadistico 2021-2"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2021_02.pdf");
        }
        else if(lista.equals("Informe estadistico 2022-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/informes_estadisticos/Informes_est_2022_01.pdf");
        }
        
    }//GEN-LAST:event_infEstadisticoActionPerformed

    private void infCaracterizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infCaracterizacionActionPerformed
        // TODO add your handling code here:
        
        String lista = infCaracterizacion.getSelectedItem().toString();
        
        if(lista.equals("Admitidos 2017-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/CARACTERIZACION_ADMITIDOS/CARACTERIZACION_ADMITIDOS_2017_01.pdf");
        }
        else if(lista.equals("Admitidos 2017-2"))
        {
            metodoURL("http://200.119.89.147/sief/cod/CARACTERIZACION_ADMITIDOS/CARACTERIZACION_ADMITIDOS_2017_02.pdf");
        }
        else if(lista.equals("Admitidos 2018-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/CARACTERIZACION_ADMITIDOS/CARACTERIZACION_ADMITIDOS_2018_01.pdf");
        }
        else if(lista.equals("Admitidos 2018-2"))
        {
            metodoURL("http://200.119.89.147/sief/cod/CARACTERIZACION_ADMITIDOS/CARACTERIZACION_ADMITIDOS_2018_02.pdf");
        }
        else if(lista.equals("Admitidos 2019-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/CARACTERIZACION_ADMITIDOS/CARACTERIZACION_ADMITIDOS_2019_01.pdf");
        }
        else if(lista.equals("Admitidos 2019-2"))
        {
            metodoURL("http://200.119.89.147/sief/cod/CARACTERIZACION_ADMITIDOS/CARACTERIZACION_ADMITIDOS_2019_02.pdf");
        }
        else if(lista.equals("Admitidos 2020-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/CARACTERIZACION_ADMITIDOS/CARACTERIZACION_ADMITIDOS_2020_01.pdf");
        }
        else if(lista.equals("Admitidos 2020-2"))
        {
            metodoURL("http://200.119.89.147/sief/cod/periodo_2022_01.php#");
        }
        else if(lista.equals("Admitidos 2021-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/CARACTERIZACION_ADMITIDOS/CARACTERIZACION_ADMITIDOS_2021_01.pdf");
        }
        else if(lista.equals("Admitidos 2021-2"))
        {
            metodoURL("");
        }
        else if(lista.equals("Admitidos 2022-1"))
        {
            metodoURL("http://200.119.89.147/sief/cod/CARACTERIZACION_ADMITIDOS/CARACTERIZACION_ADMITIDOS_2022_01.pdf");
        }


    }//GEN-LAST:event_infCaracterizacionActionPerformed

    private void comboConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboConsultarActionPerformed
        // TODO add your handling code here:
        String lista = comboConsultar.getSelectedItem().toString();
        
        if(lista.equals("Estudiantes de primer curso"))
        {
            EstudiantesPrimerCurso ventana = new EstudiantesPrimerCurso();
            String label = this.lblTipo.getText();
            ventana.setVisible(true);
            ventana.lblUsuario.setText(this.lblUsuario.getText());
            ventana.btnInsertar.setEnabled(false);
            if(label.equals("1"))
            {
                System.out.println("Admin");
                ventana.btnInsertar.setEnabled(true);
            }
            
            
        }
        else if(lista.equals("Inscritos"))
        {
            Inscritos ventana = new Inscritos();
            ventana.setVisible(true);
        }
        else if(lista.equals("Admitidos"))
        {
            Admitidos ventana = new Admitidos();
            ventana.setVisible(true);
        }
        else if(lista.equals("Matriculados"))
        {
            Matriculados ventana = new Matriculados();
            ventana.setVisible(true);
        }
        else if(lista.equals("Graduados"))
        {
            Graduados ventana = new Graduados();
            ventana.setVisible(true);
        }
            
            
            
        
    }//GEN-LAST:event_comboConsultarActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add your handling code here:
        MetodosSQL sql = new MetodosSQL();
        MiPerfil ventana = new MiPerfil();
        ventana.setVisible(true);
        ventana.lblUsuario.setText(this.lblUsuario.getText());
        
        String correo = sql.buscarCorreo(this.lblUsuario.getText());
        ventana.lblCorreo.setText(correo);
        
        

    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        
        Menu ventana = new Menu();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIEF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIEF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIEF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIEF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIEF().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JComboBox<String> comboConsultar;
    public javax.swing.JComboBox<String> funcionAdmin;
    private javax.swing.JComboBox<String> infCaracterizacion;
    private javax.swing.JComboBox<String> infEstadistico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JLabel lblNombre;
    public javax.swing.JLabel lblTipo;
    public javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
